config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }

  root 'mains#index'

  get '/commands', to: 'mains#commands', as: 'commands'
  get '/about_command/:id', to: 'mains#about_command', as: 'about_command'
  get '/about_user/:id', to: 'mains#about_user', as: 'about_user'
  get '/movies', to: 'mains#movies', as: 'movies'
  get '/participants', to: 'mains#participants', as: 'participants'
  get '/contacts', to: 'mains#contacts', as: 'contacts'
  get '/help_project', to: 'mains#help_project', as: 'help_project'


  # Роутинг поиска участников
  get '/in_commands', to: 'mains#in_commands', as: 'in_commands'
  get '/in_commands_actors', to: 'mains#in_commands_actors', as: 'in_commands_actors'
  get '/in_commands_film_crew', to: 'mains#in_commands_film_crew', as: 'in_commands_film_crew'

  get '/no_commands', to: 'mains#no_commands', as: 'no_commands'
  get '/no_commands_actors', to: 'mains#no_commands_actors', as: 'no_commands_actors'
  get '/no_commands_film_crew', to: 'mains#no_commands_film_crew', as: 'no_commands_film_crew'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :commands

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "missing/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/command.rb
class Command < ApplicationRecord
  has_many :users
  has_and_belongs_to_many :achievements

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "missing/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  belongs_to :command, optional: true
  has_and_belongs_to_many :achievements

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "missing/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def active_for_authentication?
    super && status == 'active'
  end

  def inactive_message
    if status == 'not_active'
      :not_approved
    else
      super # Use whatever other message
    end
  end

  after_update :send_email_if_status_active

  private

  def send_email_if_status_active
    if self.status_was == 'not_active' && status == 'active'
      ToAdminMailer.confirm_alert(self).deliver_now
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  protected
  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      AdminUser.all.each do |admin|
        ToAdminMailer.reg_alert(admin).deliver_now
      end
      signed_in_root_path(resource)
    else
      AdminUser.all.each do |admin|
        ToAdminMailer.reg_alert(admin).deliver_now
      end
      new_session_path(resource_name)
    end
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

  def index
  end

  def commands
    @commands = Command.all
  end

  def about_command
    @about_command = Command.find(params[:id])
    @all_command_participants = User.where(command: Command.find_by_name(@about_command.name))
  end

  def about_user
    @user = User.find(params[:id])
  end

  def movies
  end

  def participants
  end

  def contacts
  end

  def help_project
  end


  #Экшены поиска участников

  def in_commands
  end

  def no_commands
  end

  def in_commands_actors
    @in_commands_actors = User.where(role: Role.find_by_name('Актёрский_состав'), command_id: !nil, status: 'active')
  end

  def no_commands_actors
    @no_commands_actors = User.where(role: Role.find_by_name('Актёрский_состав'), command_id: nil, status: 'active')
  end

  def in_commands_film_crew
    @in_commands_film_crew = User.where(role: Role.find_by_name('Съёмочная_группа'), command_id: !nil, status: 'active')
  end

  def no_commands_film_crew
    @no_commands_film_crew = User.where(role: Role.find_by_name('Съёмочная_группа'), command_id: nil, status: 'active')
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :surname, :avatar, :description, :phone, :social_network, :email, :password,
                                 :password_confirmation, :role_id)
  end

  def account_update_params
    params.require(:user).permit(:name, :surname, :avatar, :description, :phone, :social_network, :email, :password,
                                 :password_confirmation, :current_password, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">

    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <%= link_to root_path do %>
            <%= image_tag 'логотип на главной.jpg', height: '250', width: '900' %>
        <% end %>
      </ul>
      <ul class="navbar-nav navbar-left">
        <%= link_to 'Команды', commands_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Видео', movies_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Участники', participants_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Контакты', contacts_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Помочь проекту', help_project_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to image_tag("youtube.png", :size => '30x30'), 'http://www.youtube.com', class: 'btn btn-default navbar-btn' %>
        <%= link_to image_tag("инстаграм.jpg", :size => '30x30'), 'https://www.instagram.com/kakvkino.club/', class: 'btn btn-default navbar-btn' %>
        <%= link_to image_tag("вк.jpg", :size => '30x30'), 'https://vk.com/public103899884', class: 'btn btn-default navbar-btn' %>
        <%= link_to image_tag("ок.png", :size => '30x30'), 'https://www.ok.ru/molodezhnytsentr.kbkvntamashow', class: 'btn btn-default navbar-btn' %>
        <%= link_to image_tag("фейсбук.png", :size => '30x30'), 'https://www.facebook.com/%D0%9A%D0%B0%D0%BA-%D0%B2-%D0%9A%D0%98%D0%9D%D0%9E-808950895951755/', class: 'btn btn-default navbar-btn' %>
        <% if user_signed_in? %>
            <p class="navbar-text">
              Привет, <%= link_to current_user.name, about_user_path(current_user.id) %>!
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Аккаунт <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Редактировать профиль', edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <%= link_to 'Войти', new_user_session_path, class: 'btn btn-default navbar-btn' %>
                </ul>
              </li>
            </ul>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Like in the movies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar.html.erb' %>
    <%= yield %>
  </body>
</html>

app/views/mains/about_command.html.erb
<table>
  <tr>
    <tr>Название команды: <%= @about_command.name%></tr>
      <td>О команде: <%= @about_command.description%></td>
      <td>Логогип команды: <%= image_tag @about_command.avatar.url(:thumb) %></td>
   </tr>
</table>

<div>Участники команды</div>

<% @all_command_participants.each do |participant| %>
<table>
  <tr>
    <td><%= participant.role.name %>: <%= link_to participant.name , about_user_path(participant) %> </td>
  </tr>
<% end %>
</table>

<br>
<div>Достижения команды</div>
<% @about_command.achievements.each do |achievement| %>
<table>
  <tr>
    <td><%= achievement.name%></td><br>
    <td><%= achievement.description %></td>
    <td><%= image_tag achievement.avatar.url(:thumb) %></td>
  </tr>
<% end %>
</table>

app/views/mains/about_user.html.erb
<div>Информация о пользователе</div>

<td><%= @user.name %></td> <br>
<td><%= @user.surname %></td> <br>
<td><%= @user.description %></td> <br>
<td><%= @user.phone %></td> <br>
<td><%= @user.social_network %></td> <br>
<td><%= @user.role.name %></td> <br>
<td>
  <% if @user.command != nil %>
    <%= @user.command.name  %>
  <% else %>
    <%= 'Без команды' %>
  <% end %>
</td> <br>
<td><%= image_tag @user.avatar.url %></td> <br>

<div>Достижения пользователя</div>
<% @user.achievements.each do |achievement| %>
<table>
  <tr>
    <td><%= achievement.name%></td><br>
    <td><%= achievement.description %></td>
    <td><%= image_tag achievement.avatar.url(:thumb) %></td>
  </tr>
    <% end %>
</table>

app/views/mains/commands.html.erb
<div>Команды участников</div>

<table>
  <% @commands.each do |command| %>
      <tr>
        <td><%= command.name %></td>
        <td>
          <%= link_to about_command_path(command) do %>
          <%= image_tag command.avatar.url   %> <br>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

app/views/mains/contacts.html.erb
<div>Наши контакты</div>
<div>0558 126 394</div>

app/views/mains/help_project.html.erb
<div>Помочь проекту</div>
<div>Наш кошелёк WebMoney: 0 558 126 394</div>

app/views/mains/in_commands.html.erb
<div>Участники в команде</div>
<%= link_to 'Съёмочная группа', in_commands_film_crew_path, class: 'btn btn-default navbar-btn' %>
<%= link_to 'Актёрский состав', in_commands_actors_path, class: 'btn btn-default navbar-btn' %>

app/views/mains/in_commands_actors.html.erb
<div>Актёрский состав в команде</div>
<% @in_commands_actors.each do |user| %>
    <%= link_to user.name, about_user_path(user) %>
<%end%>

app/views/mains/in_commands_film_crew.html.erb
<div>Съёмочный состав в команде</div>
<% @in_commands_film_crew.each do |user| %>
    <%= link_to user.name, about_user_path(user) %>
<%end%>

app/views/mains/index.html.erb
<div>
  Привет! Наш проект называется "Как в кино". Присоединяйся к нам!
  Зададим жару! Присоединяйся к нам! Зададим жару!Присоединяйся к нам! Зададим жару!Присоединяйся к нам!
  Зададим жару!Присоединяйся к нам! Зададим жару!Присоединяйся к нам! Зададим жару!
  Присоединяйся к нам! Зададим жару!Присоединяйся к нам! Зададим жару!Присоединяйся к нам!
  Зададим жару!Присоединяйся к нам! Зададим жару!Присоединяйся к нам! Зададим жару!Присоединяйся к нам!
  Зададим жару!
</div><br>
<br>
<br>
<div>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/upSwABrmWS8" frameborder="0" allowfullscreen></iframe>
</div>
<br>
<br>
<div>
  <%= link_to 'Подать заявку для участия в проекте', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
</div>

<br>
<div>
  Здесь будет список спонсоров
</div>

app/views/mains/movies.html.erb
<div>Здесь будут куча плееров ютубовских, возможно на плейлисты</div>

app/views/mains/no_commands.html.erb
<div>Участники без команды</div>
<%= link_to 'Съёмочная группа', no_commands_film_crew_path, class: 'btn btn-default navbar-btn' %>
<%= link_to 'Актёрский состав', no_commands_actors_path, class: 'btn btn-default navbar-btn' %>

app/views/mains/no_commands_actors.html.erb
<div>Актёрский состав без команды</div>
<% @no_commands_actors.each do |user| %>
    <%= link_to user.name, about_user_path(user) %>
<%end%>

app/views/mains/no_commands_film_crew.html.erb
<div>Съёмочный состав без команды</div>
<% @no_commands_film_crew.each do |user| %>
    <%= link_to user.name, about_user_path(user) %>
<%end%>

app/views/mains/participants.html.erb
<div>Поиск участников проекта</div>

<%= link_to 'В команде', in_commands_path, class: 'btn btn-default navbar-btn' %>
<%= link_to 'Без команды', no_commands_path, class: 'btn btn-default navbar-btn' %>